config/routes.rb
PinterestClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :new, :show, :update]
  resource :session, :only => [:create, :destroy, :new]

  namespace :api, :defaults => { :format => :json } do
    resources :boards
    resources :pins
    resources :boards_pins
  end

  root :to => "root#root"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :fname, :lname, :password
  attr_reader :password

  validates :email, :fname, :lname, :session_token, :presence => true
  validates :password_digest, :presence => { :message => "Password cannot be blank"}
  validates :password, :length => { :minimum => 6, :allow_nil => true }

  before_validation :ensure_session_token

  has_many :boards
  has_many :boards_pins, :through => :boards, :source => :boards_pins
  has_many :pins, :through => :boards, :source => :pins

  def self.find_by_credentials(params)
    user = User.find_by_email(params[:email])
    return nil if user.nil?
    user.is_password?(params[:password]) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.include(:boards)
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to root_url
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.includes({:boards => :pins}, :pins, :boards_pins).find(params[:id])
      @boards_pins = users_pins(@user)

      respond_to do |format|
        format.json { render "show" }
      end
    else
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:board])
      render :json => @user
    else
      render :json => @user.errors.full_messages
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    current_user == user
  end

  def users_pins(user)
    boards = user.boards.includes(:boards_pins, :pins)
    pins = []

    boards.each do |board|
      pins << board.boards_pins
    end
    pins.flatten!
  end
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>
<div class="container">
<form id="new-user-form" action="<%= action %>" method="post">

  <div class="row">
    <div class="col-sm-2 col-sm-offset-4">
      <input
           name="_method"
           type="hidden"
           value="<%= method %>">
      <input
         name="authenticity_token"
         type="hidden"
         value="<%= form_authenticity_token %>">

      <div class="form-group" id="fname">  
        <input
          class="form-control"
          id="user_fname"
          name="user[fname]"
          type="text"
          placeholder="First Name">
      </div>
    </div>
  
    <div class="col-sm-2">
      <div class="form-group" id="lname">  
        <input
          class="form-control" 
          id="user_lname"
          name="user[lname]"
          type="text"
          placeholder="Last Name">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-group"  id="email">  
        <input
          class="form-control" 
          id="user_email"
          name="user[email]"
          type="email"
          placeholder="Email Address">
      </div>
  
      <div class="form-group" id="password">  
        <input
           class="form-control" 
           id="user_password"
           name="user[password]"
           type="password"
           placeholder="Password">
      </div>
      
      <div class="form-actions">
        <div class="col-sm-7 col-sm-offset-5">
          <input type="submit" class="hidden">
          <button onclick="window.location.href='/'" class="btn btn-defaul">Cancel</button>
          <button type="submit" class="btn btn-danger"><%= message %></button>
        </div>
      </div>
    </div>
  </div>
</form>
</div>

<script>
  $(document).ready(function () {
    $("#new-user-form").validate({
      rules: {
        "user[fname]": { required: true },
        "user[lname]": { required: true },
        "user[email]": { required: true, email: true },
        "user[password]": { required: true, minlength: 6 }
      },

      messages: {
        "user[fname]": "Please enter your first name.",
        "user[lname]": "Please enter your last name.",
        "user[email]": "Please enter email.",
        "user[password]": "Please enter password."
      },

      highlight: function(element, errorClass, validClass) {
        $("#fname").addClass("has-error");
        $("#lname").addClass("has-error");
        $("#email").addClass("has-error");
        $("#password").addClass("has-error");
      },
      
      unhighlight: function(element, errorClass, validClass) {
        $("#fname").removeClass("has-error");
        $("#lname").removeClass("has-error");
        $("#email").removeClass("has-error");
        $("#password").removeClass("has-error");      }
    });
  });
</script>

app/views/users/new.html.erb
<h1 align="center">Sign up</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.fname %></h1>

<p>Hello, dear user!</p>

<ul>
  <% @boards.each do |board| %>
  	<li><a href="#/boards/<%= board.id %>"><%= board.name %></a></li>
  <% end %>
</ul>