config/routes.rb
PinterestClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :new, :show, :update]
  resource :session, :only => [:create, :destroy, :new]

  namespace :api, :defaults => { :format => :json } do
    resources :boards
    resources :pins
    resources :boards_pins
  end

  root :to => "root#root"
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def root
    render "root"
  end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/_home.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="header">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand">
        <a class="navbar-brand" href="/">
          C <i class="fa fa-circle"></i> RKBOARD
        </a>
      </a>
    </div>
  </div>
</div>


<div id="headerwrap">
  <div id="layer">
    <div class="row centered">
      <div class="container">

      <div class="col-lg-8 col-lg-offset-2">
        <h1>Save all the stuff you <b>love</b>!!</h1>

        <p style="margin-top:30px; margin-bottom:30px;">
        <a class="btn btn-primary"
           href="<%= new_user_url %>"
           role="button">Sign Up</a>
        </p>

        <h4 style="color: white"><b>
          Already have an account? <%= link_to "Log in now", new_session_url, :class => "img-text" %>
          <br>
          Or sign in as a <b><a href="#" id="example-sign-in" class="img-text">GUEST</a></b>
        </b></h4>
      </div>
    </div>
  </div>
</div>
</div>

<div class="container w">
  <div class="row centered">
    <br><br>
    <div class="col-lg-4 col-lg-offset-2">
      <i class="fa fa-thumb-tack"></i>
      <h4>PIN</h4>
      <p>Pin your favorite stuff (recipes! articles! travel ideas!) right here on Corkboard.</p>
    </div><!-- col-lg-4 -->

    <div class="col-lg-4">
      <i class="fa fa-laptop"></i>
      <h4>BROWSE</h4>
      <p>Browse users' boards and pins - save and search for what you like.</p>
    </div><!-- col-lg-4 -->
  </div><!-- row -->
  <br>
  <br>
</div><!-- container -->


<!-- example account login -->
<form id="sign-in-form" action="<%= session_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <input
      class="form-control"
      type="hidden"
      id="email"
      name="user[email]"
      value="guest@email.com">

    <input
      class="form-control"
      type="hidden"
      id="password"
      name="user[password]"
      value="password">
</form>

<div class="bottom-section"></div>

<script>
  $("#example-sign-in").click(function(event) {
    debugger;
    event.preventDefault();
    $("#sign-in-form").trigger("submit");
  })
</script>

app/views/root/root.html.erb
<div id="header">
</div>

<div id="content">

<% if !current_user %>
  <%= render "home" %>
<% end %>

</div>